language: node_js
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
jobs:
  include:
    - name: test
      node_js:
        - "8"
        - "7"
      script: npm run generate-docs && npm run test && npm run e2e-test
    - name: bundle
      node_js: 8
      # if: branch = master # TODO: Uncomment this
      os: osx # Need to have an OSX build to build XCUITestDriver
      script: npm --production install && npm run zip-and-upload
